# ML-03 — Frame Your Lane as an ML Task

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

In [24]:
# 1. My lane as an ML task

ml_task_type = "Scoring"

why = """
My chosen lane is Content Refresh Opportunity Scoring.

This is a scoring problem because the goal is to assign every content page
a priority score that indicates how urgently it should be refreshed.
Pages with higher scores should be refreshed first.
"""

print("ML Task Type:", ml_task_type)
print(why)

ML Task Type: Scoring

My chosen lane is Content Refresh Opportunity Scoring.

This is a scoring problem because the goal is to assign every content page
a priority score that indicates how urgently it should be refreshed.
Pages with higher scores should be refreshed first.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

In [25]:
# 2. Target or Proxy

target = "Refresh Priority Score"

proxy = """
There is no direct label saying whether a page needs refreshing.

The target is estimated using a proxy based on CTR,
traffic trend, impressions and engagement.

Pages with declining performance receive higher refresh scores.
"""

print("Target:", target)
print(proxy)

Target: Refresh Priority Score

There is no direct label saying whether a page needs refreshing.

The target is estimated using a proxy based on CTR,
traffic trend, impressions and engagement.

Pages with declining performance receive higher refresh scores.

## 3. Success metric

*One metric you can defend. What number means 'good'?*

In [26]:
# 3. Success Metric

success_metric = """
A good model should correctly rank pages that benefit the most from refreshing.

Possible metrics:
- Precision@K
- NDCG
- Improvement in CTR after refresh
"""

print(success_metric)

A good model should correctly rank pages that benefit the most from refreshing.

Possible metrics:
- Precision@K
- NDCG
- Improvement in CTR after refresh

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [27]:
!pwd

/content

In [28]:
!ls

flyrank-ml-internship-starter  sample_data

In [29]:
!git clone https://github.com/flyrank-bih/flyrank-ml-internship-starter.git

fatal: destination path 'flyrank-ml-internship-starter' already exists and is not an empty directory.

In [30]:
!find . -name "content_refresh_anonymized.csv"

./flyrank-ml-internship-starter/data/raw/content_refresh_anonymized.csv

In [31]:
import pandas as pd

df = pd.read_csv(
    "flyrank-ml-internship-starter/data/raw/content_refresh_anonymized.csv"
)

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [32]:
!find . -name "content_refresh_anonymized.csv"

./flyrank-ml-internship-starter/data/raw/content_refresh_anonymized.csv

In [33]:
import pandas as pd

# Load dataset
df = pd.read_csv("flyrank-ml-internship-starter/data/raw/content_refresh_anonymized.csv")

# Show first 5 rows
df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [34]:
print("Number of rows:", len(df))
print("\nColumns:")
print(df.columns)

print("\nUnit of analysis:")
print("One row represents one content page.")

Number of rows: 30000

Columns:
Index(['content_id', 'client_id', 'search_volume', 'competition',
       'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count',
       'char_count', 'provider_used', 'model_used', 'impressions_90d',
       'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d',
       'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d',
       'days_with_impressions', 'days_with_sessions', 'impressions_last_30d',
       'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d',
       'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier',
       'age_tier_order', 'days_since_last_update', 'freshness_tier',
       'word_count_tier', 'char_count_tier', 'ctr', 'avg_position',
       'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier',
       'position_tier', 'trend_direction', 'trend_pct'],
      dtype='object')

Unit of analysis:
One row represents one content page.

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

In [35]:
why_ml = """
A fixed rule such as 'refresh every page with CTR below 0.4'
is too simple because content performance depends on many factors.

Machine learning can combine multiple signals like CTR,
impressions, traffic trend and engagement to assign
a better refresh priority score.

This helps prioritize the pages that are most likely
to improve after being refreshed.
"""

print(why_ml)

A fixed rule such as 'refresh every page with CTR below 0.4'
is too simple because content performance depends on many factors.

Machine learning can combine multiple signals like CTR,
impressions, traffic trend and engagement to assign
a better refresh priority score.

This helps prioritize the pages that are most likely
to improve after being refreshed.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.